//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentImage
    {
        public int ID { get; set; }
        public int ApartmentID { get; set; }
        public string ImageName { get; set; }
        public string Description { get; set; }
        public bool IsMain { get; set; }
    }
}
