//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public int ApartmentType { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ResponsibleUser { get; set; }
        public int Capacity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Coordinates { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> LastReservationDate { get; set; }
        public string DescriptionENG { get; set; }
    }
}
