//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMaster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MasterModelEntities : DbContext
    {
        public MasterModelEntities()
            : base("name=MasterModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<ApartmentImage> ApartmentImages { get; set; }
        public virtual DbSet<ApartmentDetail> ApartmentDetails { get; set; }
    
        public virtual ObjectResult<sp_GetApartments_Result> sp_GetApartments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetApartments_Result>("sp_GetApartments");
        }
    }
}
